### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException: Unable to make field jdk.inte rnal.ref.PhantomCleanable

### ISSUE THREAD

**Issue by stephankoelle** [jbellis/jamm#45]
The JVM (openjdk 15) sometimes has internal  PhantomCleanable those throw an exception 

```
Jamm must be set as -javaagent: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field jdk.inte
rnal.ref.PhantomCleanable jdk.internal.ref.PhantomCleanable.prev accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @1ce92674: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.reflect.In
accessibleObjectException: Unable to make field jdk.internal.ref.PhantomCleanable jdk.internal.ref.PhantomCleanable.prev accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @1ce92674
        at org.github.jamm.MemoryMeterBase.measureDeep(MemoryMeterBase.java:129) [jamm-0.4.0.jar:0.4.0-SNAPSHOT]

```

**Comment by stephankoelle** [comment]
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field jdk.internal.ref.PhantomCleanable jdk.internal.ref.PhantomCleanable.prev accessible: module java.base does not "opens jdk.internal.ref" to unnamed module @1ce92674
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:361) [java.base:]
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:301) [java.base:]
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177) [java.base:]
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171) [java.base:]
        at org.github.jamm.MemoryMeterBase.declaredClassFields0(MemoryMeterBase.java:241) [jamm-0.4.0.jar:0.4.0-SNAPSHOT]
        ... 83 more

```

**Comment by stephankoelle** [comment]
#46

**Comment by blerer** [comment]
Thanks for reporting this problem. This problem is now fixed.
