### ISSUE TITLE
java.lang.IllegalAccessException on java.text.DigitList and com.google.protobuf.MapEntry$Metadata

### ISSUE THREAD

**Issue by MikaelSmith** [jbellis/jamm#56]
I'm using https://github.com/jbellis/jamm/commit/887e3c0814fb0ff8bbf78bb5481ecdf4e2305769 (current HEAD of master branch) with Java 8 (on Ubuntu 16.04) and running into some unexpected exceptions:
```
org.github.jamm.CannotAccessFieldException: The value of the descriptor field from class org.apache.kudu.shaded.com.google.protobuf.MapEntry$Metadata cannot be retrieved
	at org.github.jamm.PlainReflectionAccessor.getFieldValue(PlainReflectionAccessor.java:21)
	at org.github.jamm.MemoryMeter.getFieldValue(MemoryMeter.java:381)
	at org.github.jamm.MemoryMeter.addFieldChildren(MemoryMeter.java:353)
	at org.github.jamm.MemoryMeter.measureDeep(MemoryMeter.java:337)
	at org.apache.impala.catalog.local.CatalogdMetaProvider$SizeOfWeigher.weigh(CatalogdMetaProvider.java:2056)
...
Caused by: java.lang.IllegalAccessException: Class org.github.jamm.PlainReflectionAccessor can not access a member of class org.apache.kudu.shaded.com.google.protobuf.MapEntry$Metadata with modifiers "public final"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.get(Field.java:390)
	at org.github.jamm.PlainReflectionAccessor.getFieldValue(PlainReflectionAccessor.java:18)
	... 19 more
```
and
```
org.github.jamm.CannotAccessFieldException: The value of the digits field from class java.text.DigitList cannot be retrieved
	at org.github.jamm.PlainReflectionAccessor.getFieldValue(PlainReflectionAccessor.java:21)
	at org.github.jamm.MemoryMeter.getFieldValue(MemoryMeter.java:381)
	at org.github.jamm.MemoryMeter.addFieldChildren(MemoryMeter.java:353)
	at org.github.jamm.MemoryMeter.measureDeep(MemoryMeter.java:337)
	at org.apache.impala.catalog.local.CatalogdMetaProvider$SizeOfWeigher.weigh(CatalogdMetaProvider.java:2056)
...
Caused by: java.lang.IllegalAccessException: Class org.github.jamm.PlainReflectionAccessor can not access a member of class java.text.DigitList with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.get(Field.java:390)
	at org.github.jamm.PlainReflectionAccessor.getFieldValue(PlainReflectionAccessor.java:18)
	... 19 more
```

The exact reason they're not accessible is unclear from the error message. If there's no way to avoid this error for these classes, it would still be useful to get a partial measurement.

**Comment by MikaelSmith** [comment]
These are what I found for relevant source code:
- https://github.com/protocolbuffers/protobuf/blob/v3.21.7/java/core/src/main/java/com/google/protobuf/MapEntry.java
- https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/java/text/DigitList.java

**Comment by blerer** [comment]
@MikaelSmith Thanks for the report. Effectively there is a problem with the code when we try to read a public field in a non public class. I will push a fix.
